server:
  port: 8088
spring:
    application:
        name: spring-websocket-chat-demo
    devtools:
      livereload:
        enabled: true
    datasource:
      url: jdbc:mysql://localhost:3306/chat?allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: 12345678
# Mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDel # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
# 在线文档配置
springdoc:
  swagger-ui:
    path: /s-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      display-name: 'showcase'
      paths-to-match:
        - '/**'
      packages-to-scan:
        - me.wangj.controller
knife4j:
  enable: true
